model = "gpt-5-codex"
model_reasoning_effort = "high"

[tools]
web_search = true

[mcp_servers.context7]
args = [
    "-y",
    "@upstash/context7-mcp",
    "--api-key",
    "ctx7sk-e91b8b04-09f3-40fd-823e-db628fecd807",
]
command = "npx"

[mcp_servers.serena]
args = [
    "--from",
    "git+https://github.com/oraios/serena",
    "serena",
    "start-mcp-server",
    "--context",
    "codex",
]
command = "uvx"

[mcp_servers.github]
args = [
    "--transport",
    "streamablehttp",
    "-H",
    "Authorization",
    "Bearer GitHub„ÅÆPersonal Access Token",
    "https://api.githubcopilot.com/mcp/",
]
command = "mcp-proxy"
